k3os:
  k3s_args:
  - server
  - "--disable"
  - servicelb,traefik,local-storage,coredns
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
write_files:
- path: /etc/udev/rules.d/81-uud3.rules
  content: >
    ACTION=="add", SUBSYSTEM=="block",
    ENV{ID_PART_ENTRY_TYPE}=="26758745-8ec9-4d5f-9f79-9e2339ad253d",
    RUN+="/bin/mount -o X-mount.mkdir /dev/%k /media/%E{ID_FS_UUID}"

    ACTION=="remove", SUBSYSTEM=="block",
    ENV{ID_PART_ENTRY_TYPE}=="26758745-8ec9-4d5f-9f79-9e2339ad253d",
    RUN+="/bin/umount -l /media/%E{ID_FS_UUID}", RUN+="/bin/rmdir /media/%E{ID_FS_UUID}"
